### ISSUE TITLE
Dockerイメージのバージョンを指定する

### ISSUE THREAD

**Issue by translucens** [kz-kz/practice_crypto#1]
下記のように書かれているので（2019/05/21現在） `latest` タグが付いている `8.0.16` が使用されますが、今後新しいバージョンが出たときに再現性がなくなりますし、まだまだ8.0系は使えない環境も多いかと思います。 `mysql:5.7.26` のように特定バージョンを指定するのがよいでしょう。
```
docker pull mysql
```

**Comment by kz-kz** [comment]
修正してみました
https://github.com/kz-kz/practice_crypto/pull/5#issue-282229164
